name: Format Code

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up V
        uses: vlang/setup-v@v1.1
        with:
          check-latest: true

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Format Code
        run: v fmt -w ./

      - name: Push To GitHub
        continue-on-error: true
        run: |
          git pull
          git add ./
          git commit --amend
          git push
